name:                haskell-addict
version:             0.1.1
github:              "WhiteCat6142/haskell-addict"
license:             MIT
author:              "WhiteCat6142"
maintainer:          "whitecat6142+git@gmail.com"
copyright:           "2022 WhiteCat6142"

description:         Please see the README on GitHub at <https://github.com/WhiteCat6142/haskell-addict>

dependencies:
- vector
- base >= 4.7 && < 5
- random
- mwc-random
- Chart
- Chart-cairo

executables:
  art1-exe:
    main:                art1.hs
    source-dirs:         haskell-addict
  bs-exe:
    main:                bs.hs
    source-dirs:         haskell-addict
  hanoi-exe:
    main:                hanoi.hs
    source-dirs:         haskell-addict
  fib-exe:
    main:                fib.hs
    source-dirs:         haskell-addict
  quiz-exe:
    main:                quiz.hs
    source-dirs:         haskell-addict
  convex-exe:
    main:                convex.hs
    source-dirs:         haskell-addict
