name: Stack Build
on: [push]
jobs:
  build:
        name: Greeting
        runs-on: ubuntu-22.04
        env:
          LANG: C
        steps:
        - uses: actions/checkout@v3
          with:
            path: haskell-addict
        - uses: haskell/actions/setup@v2
          with:
            ghc-version: '8.8.4'
            cabal-version: '3.0.1.0'
            enable-stack: true
            stack-version: 'latest'
        - run: |
            cp haskell-addict/package.yaml .
            cp haskell-addict/stack.yaml .
            stack --system-ghc build
            stack --system-ghc exec -- fib-exe
